In [123]:
# Get the sqlite database path

import nhs_waiting_lists as nhs
from nhs_waiting_lists.constants import ALL_TREATMENT_CODES

> Over the two previous complete financial years (from April 2023 to March this year), there have been on average 244,578 unreported removals a month (unadjusted for working days), and 7,566,344 incomplete pathways (making up the reported waiting list) a month. This means that, on average, unreported removals equate to around 3% of the size of the waiting list.

Source: <https://www.nuffieldtrust.org.uk/news-item/why-is-the-planned-care-waiting-list-coming-down-and-what-does-the-data-really-tell-us?dm_i=21A8,909FB,1TOIL8,11MABM,1>

In [124]:
# get the consolidated data corresponding to the previously published estimates

consolidated_df = nhs.get_consolidated_df2(
    "2023-04",
    "2025-03",
    [],
    ALL_TREATMENT_CODES,
    # ["C_999"],
)

consolidated_df.head()

,period,provider,treatment,untreated,new_periods,incomplete,incomplete_prev,completed,total_treatable
0,2024-06,8KL73,C_301,NaN,139,70,NaN,101,NaN
1,2024-07,8KL73,C_301,-26.0,141,55,70.0,130,211.0
2,2024-08,8KL73,C_301,3.0,122,51,55.0,129,177.0
3,2023-04,A0C5S,C_130,74.0,116,160,120.0,150,236.0
4,2023-05,A0C5S,C_130,73.0,120,163,160.0,190,280.0

In [120]:
consolidated_c_999_df = nhs.get_consolidated_df2(
    "2023-04",
    "2025-03",
    [],
    ["C_999"],
)

consolidated_c_999_df.head()

,period,provider,treatment,untreated,new_periods,incomplete,incomplete_prev,completed,total_treatable
0,2024-06,8KL73,C_999,NaN,139,70,NaN,101,NaN
1,2024-07,8KL73,C_999,-26.0,141,55,70.0,130,211.0
2,2024-08,8KL73,C_999,3.0,122,51,55.0,129,177.0
3,2023-04,A0C5S,C_999,74.0,116,160,120.0,150,236.0
4,2023-05,A0C5S,C_999,73.0,120,163,160.0,190,280.0

In [121]:
import pandas as pd

other_result: pd.DataFrame = consolidated_df.groupby(['period']).sum()

# need to calcualte the pct after the aggregation
other_result["unexplained_pct"] = other_result["untreated"] / other_result["total_treatable"]
print(f"untreated mean: {other_result['untreated'].mean()}")
print(f"incomplete mean: {other_result['incomplete'].mean()}")
print(f"incomplete mean: {other_result['incomplete'].mean()}")

untreated mean: -241197.58333333334
incomplete mean: 7595552.375
incomplete mean: 7595552.375

In [122]:
other_result_c_999: pd.DataFrame = consolidated_c_999_df.groupby(['period']).sum()

# need to calcualte the pct after the aggregation
other_result_c_999["unexplained_pct"] = other_result_c_999["untreated"] / other_result_c_999["total_treatable"]
print(f"untreated mean: {other_result_c_999['untreated'].mean():0.2f}")
print(f"incomplete mean: {other_result_c_999['incomplete'].mean():0.2f}")

untreated mean: -240622.67
incomplete mean: 7595552.38

In [123]:
for i in range(5):
    start_period = f"2023-{2+i:>02}"
    end_period = f"2025-{1+i:>02}"
    print(f"from {start_period} to {end_period}")

    df_raw = nhs.get_consolidated_df2(
        start_period,
        end_period,
        [], # give all providers
        # ["C_999"], # use 'total' treatment code
        ALL_TREATMENT_CODES,
    )
    other_result_c_999: pd.DataFrame = df_raw.groupby(['period']).sum()
    print(f"untreated mean: {other_result_c_999['untreated'].mean():0.2f}")
    print(f"incomplete mean: {other_result_c_999['incomplete'].mean():0.2f}")
    print(other_result_c_999['untreated'].mean()/other_result_c_999['incomplete'].mean())
    print("")

from 2023-02 to 2025-01
untreated mean: -241019.79
incomplete mean: 7584010.79
-0.03177999059963099

from 2023-03 to 2025-02
untreated mean: -241249.67
incomplete mean: 7591801.50
-0.031777657340838886

from 2023-04 to 2025-03
untreated mean: -241197.58
incomplete mean: 7595552.38
-0.03175510765052599

from 2023-05 to 2025-04
untreated mean: -245047.38
incomplete mean: 7594620.67
-0.03226591369803767

from 2023-06 to 2025-05
untreated mean: -247598.25
incomplete mean: 7589931.29
-0.032621935625668896