---
title: Ranking Large Acute trusts by unreported removals
author: Tom Hodder
abstract: |
    The NHS has published Referral to Treatment (RTT) waiting times data since 2007, based on monthly submissions from organisations providing consultant-led care. Each submission reports the number of new RTT referrals, the number of pathways reaching a clock-stop during the month, and the number of incomplete pathways remaining at month-end. The aggregate of these incomplete pathways is widely reported as the NHS “waiting list”.

    Taken together, these quantities imply a simple accounting identity: the number of incomplete pathways at the start of the month, plus new referrals, minus completed pathways, should equal the number of incomplete pathways at month-end. In practice, this identity does not hold. The residual is typically negative, indicating a net removal of pathways that is not disaggregated or attributed in the published RTT dataset—commonly described as “unreported removals”.

    Previous analysis has suggested that such unreported removals average around 3% nationally. In this preliminary analysis, I show that the mean unreported removal rate for Large Acute Trusts, excluding MSEFT, in 2024 was 2.83%. I then examine Mid and South Essex NHS Foundation Trust (MSEFT), which exhibits an unreported removal rate of 8.67% - approximately three times the baseline average—corresponding to around 127,000 pathway removals beyond what would be expected for a comparable trust.


echo: false
output: false
format:
  pdf:
    keep-tex: true
    toc: false
    number-sections: false
    papersize: A4
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm
jupyter: python3
bibliography: nhs_rtt_pathways.bib
---

In [1]:
# Get the sqlite database path
#| echo: false

from pathlib import Path

import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text, bindparam

from nhs_waiting_lists import (
    __app_name__,
)
from nhs_waiting_lists.constants import LARGE_ACUTE_PROVIDER_CODES, TOTAL_ONLY_TREATMENT_CODES
from nhs_waiting_lists.constants import proj_db_path, DB_FILE
from nhs_waiting_lists.utils.xdg import XDGBasedir

project_root = Path(XDGBasedir.get_data_dir(__app_name__))

DB_PATH = project_root / proj_db_path / DB_FILE
FILES_DIR = project_root / "files"

engine = create_engine(f"sqlite:///{DB_PATH}")

# Get the 23 large acute trust provider codes, identified by the ranking table csv
PROVIDER_CODES = LARGE_ACUTE_PROVIDER_CODES

# Get the C_999 meta-treatment code which aggregates all other treatment codes
TREATMENT_CODES = TOTAL_ONLY_TREATMENT_CODES
# TREATMENT_CODES = ALL_TREATMENT_CODES

#
# provider_code = "RAJ"
# treatment_code = "C_110"

In [2]:
#| echo: false
#| output: false

## Retrieve all the provider rtt summary data

consolidated_query = text("""
                          SELECT i.period,
                                 i.provider,
                                 i.treatment,
                                 i.untreated       AS untreated,
                                 i.new_periods     AS new_periods,
                                 i.incomplete,
                                 i.incomplete_prev AS incomplete_prev,
                                 i.treated         AS treated,
                              p.provider_name
                          FROM consolidated AS i
                                   JOIN provider AS p ON i.provider = p.provider
                          WHERE i.provider IN :provider_codes
                            AND i.treatment IN :treatment_codes
                            AND i.period >= '2024-01'
                            AND i.period <= '2024-12'
                            AND subtype = 'Acute - Large'
                          ORDER BY i.provider ASC, i.period ASC; \
                          """).bindparams(
    bindparam('provider_codes', expanding=True),
    bindparam('treatment_codes', expanding=True)
)

consolidated_df = pd.read_sql(consolidated_query, engine, params={
    'provider_codes': PROVIDER_CODES,
    'treatment_codes': TREATMENT_CODES}
                              )  # type: ignore[arg-type]

consolidated_df["period"] = pd.to_datetime(consolidated_df["period"], errors="coerce")

# valid = (consolidated_df['incomplete_prev'] > 100) & (consolidated_df['new_periods'] > 30)
# consolidated_df = consolidated_df.loc[valid].copy()

In [3]:
# Echo the base df before applying style sheets
#| echo: false
#| output: false

other_result: pd.DataFrame = consolidated_df.groupby(['period', 'provider'])[
    ['incomplete_prev', 'new_periods', 'treated', 'untreated', "incomplete"]].sum().reset_index()

other_result["total_pathways"] = other_result["incomplete_prev"] + other_result["new_periods"]

other_result["unexplained"] = other_result["incomplete"] - (
        other_result["incomplete_prev"] + other_result["new_periods"] - other_result["treated"])

other_result["unexplained_pct"] = other_result["untreated"] / other_result["total_pathways"]

other_result["expected_pathways"] = other_result["incomplete_prev"] + other_result["new_periods"] - other_result[
    "treated"]

other_result["actual_pathways"] = other_result["incomplete"]

df_sorted = other_result.sort_values(by=['unexplained_pct'])[["period", "provider", "unexplained_pct", "unexplained"]]
df_top_20 = df_sorted.head(10)
df_final = df_top_20.reset_index(drop=True)
df_final

      period provider  unexplained_pct  unexplained
0 2024-04-01      RHW        -0.160402        -6998
1 2024-01-01      RHW        -0.157235        -6899
2 2024-10-01      RHW        -0.153375        -6941
3 2024-07-01      RHW        -0.141166        -6095
4 2024-03-01      RHW        -0.127510        -5665
5 2024-12-01      RHW        -0.121442        -5432
6 2024-05-01      RHW        -0.119391        -4994
7 2024-02-01      RHW        -0.113517        -4955
8 2024-06-01      RHW        -0.113284        -4779
9 2024-07-01      RAJ        -0.106382       -22639

In [4]:
other_result.sort_values(by=['unexplained'])[["period", "provider", "unexplained_pct", "unexplained"]].head(20).reset_index(drop=True)

       period provider  unexplained_pct  unexplained
0  2024-07-01      RAJ        -0.106382       -22639
1  2024-03-01      RAJ        -0.101640       -21245
2  2024-10-01      RAJ        -0.094658       -19801
3  2024-01-01      RAJ        -0.094100       -19284
4  2024-11-01      RAJ        -0.092199       -19120
5  2024-09-01      RAJ        -0.087315       -18304
6  2024-05-01      RAJ        -0.085040       -17804
7  2024-12-01      RAJ        -0.084992       -17062
8  2024-06-01      RAJ        -0.077418       -16160
9  2024-02-01      RAJ        -0.078927       -16091
10 2024-04-01      RAJ        -0.075691       -15461
11 2024-08-01      RAJ        -0.060861       -12437
12 2024-05-01      RTE        -0.105537        -9553
13 2024-03-01      RTE        -0.098471        -9241
14 2024-10-01      RTE        -0.087096        -8108
15 2024-07-01      RTE        -0.086315        -7983
16 2024-01-01      RTE        -0.085130        -7966
17 2024-12-01      RTE        -0.086510        -7851
18 2024-02-01      RWH        -0.100713        -7302
19 2024-08-01      RTE        -0.079707        -7204

In [5]:
all_provider_rankings: pd.DataFrame = consolidated_df.groupby(['provider','provider_name'])[
    ['incomplete_prev', 'new_periods', 'treated', 'untreated', "incomplete"]].sum().reset_index()

all_provider_rankings["total_pathways"] = all_provider_rankings["incomplete_prev"] + all_provider_rankings["new_periods"]

all_provider_rankings["unexplained"] = all_provider_rankings["incomplete"] - (
        all_provider_rankings["incomplete_prev"] + all_provider_rankings["new_periods"] - all_provider_rankings["treated"])

all_provider_rankings["unexplained_pct"] = all_provider_rankings["untreated"] / all_provider_rankings["total_pathways"]

all_provider_rankings["expected_pathways"] = all_provider_rankings["incomplete_prev"] + all_provider_rankings["new_periods"] - all_provider_rankings[
    "treated"]

all_provider_rankings["actual_pathways"] = all_provider_rankings["incomplete"]


all_provider_rankings.sort_values(by=['unexplained'])[["provider",'provider_name', "unexplained_pct", "unexplained"]].head(10).reset_index(drop=True)

,provider,provider_name,unexplained_pct,unexplained
0,RAJ,Mid and South Essex NHS Foundation Trust,-0.086708,-215408
1,RTE,Gloucestershire Hospitals NHS Foundation Trust,-0.079950,-88038
2,RHW,Royal Berkshire NHS Foundation Trust,-0.125333,-65209
3,RJ2,Lewisham and Greenwich NHS Trust,-0.044870,-44480
4,RXR,East Lancashire Hospitals NHS Trust,-0.041111,-41632
5,R0B,South Tyneside and Sunderland NHS Foundation T...,-0.037242,-35621
6,RDE,East Suffolk and North Essex NHS Foundation Trust,-0.025792,-33424
7,RWH,East and North Hertfordshire NHS Trust,-0.036438,-30656
8,REF,Royal Cornwall Hospitals NHS Trust,-0.042675,-29250
9,RTF,Northumbria Healthcare NHS Foundation Trust,-0.054647,-28307

In [6]:
all_provider_rankings.sort_values(by=['unexplained_pct'])[["provider",'provider_name', "unexplained_pct", "unexplained"]].head(10).reset_index(drop=True)

,provider,provider_name,unexplained_pct,unexplained
0,RHW,Royal Berkshire NHS Foundation Trust,-0.125333,-65209
1,RAJ,Mid and South Essex NHS Foundation Trust,-0.086708,-215408
2,RTE,Gloucestershire Hospitals NHS Foundation Trust,-0.079950,-88038
3,RTF,Northumbria Healthcare NHS Foundation Trust,-0.054647,-28307
4,RJ2,Lewisham and Greenwich NHS Trust,-0.044870,-44480
5,REF,Royal Cornwall Hospitals NHS Trust,-0.042675,-29250
6,RXR,East Lancashire Hospitals NHS Trust,-0.041111,-41632
7,R0B,South Tyneside and Sunderland NHS Foundation T...,-0.037242,-35621
8,RWH,East and North Hertfordshire NHS Trust,-0.036438,-30656
9,RVJ,North Bristol NHS Trust,-0.033285,-23393

In [7]:
(df_final.style.format(precision=2, thousands=",", decimal=".")
 .format('{:.2%}', subset=["unexplained_pct"])
 .format(lambda v: v.strftime("%Y-%m"), subset=["period"])
 )

In [8]:
#| echo: false
#| output: true

(other_result[
     [
         "period",
         "actual_pathways",
         "expected_pathways",
         "unexplained",
         "total_pathways",
         "unexplained_pct",
     ]]
 .style.relabel_index(
    [
        "",
        'Observed<br>Incomplete<br>Pathways',
        'Expected<br>Incomplete<br>Pathways',
        'Unreported<br>Change',
        'Treatable<br>Pathways',
        'Unreported<br>%'
    ], axis=1).hide(axis='index')
 .format(precision=3, thousands=",", decimal=".")
 .format('{:.2%}', subset=["unexplained_pct"])
 .format(lambda v: v.strftime("%Y-%m"), subset=["period"])
 )