In [18]:
import json
import warnings
from pathlib import Path
from pandas.errors import PerformanceWarning

from nhs_waiting_lists import (
    __app_name__,
)
from nhs_waiting_lists.utils.xdg import XDGBasedir

warnings.simplefilter(action="ignore", category=PerformanceWarning)
import pandas as pd
from nhs_waiting_lists.core.waiting_list_db import WaitingListsDB
from scripts.excel_parsing_olde.parse_nhs_data import load_data_to_database2
from nhs_waiting_lists.utils.loader_utils import clean_wtt_rows

from nhs_waiting_lists.utils.loader_utils import fiscal_to_calendar, parse_rtt_period

db = WaitingListsDB()

In [19]:

project_root = Path(XDGBasedir.get_data_dir(__app_name__))
with open(project_root / "files/downloadsrtt-waiting-times.jsonl") as f:
    is_looping = True
    for line in f:
        data = json.loads(line)
        for foo in data["files"]:
            print(f"file is {project_root / 'files' / foo['path']}")

            period = foo["period"]

            if period < "2021-04-01":
                continue

            if period < "2017-10":
                """
                olde format with pre-column header front matter
                """
                df = pd.read_csv(
                    project_root / 'files' / foo['path'],
                    skiprows=2
                )
                df["Period"] = df.apply(fiscal_to_calendar, axis=1)
            else:
                df = pd.read_csv(
                    project_root / 'files' / foo['path'],
                    skiprows=0,
                    converters={"Period": parse_rtt_period}
                )

            df = clean_wtt_rows(df)

            bad_rows = df[
                (df["diff_total"].abs() > 0.01) | (df["diff_total_all"].abs() > 0.01)
                ]

            if len(bad_rows) > 0:
                # print(f"Bad rows: {bad_rows}")
                is_looping = False
                break  # break out of the inner loop

            cols_to_drop = ["wait_sum", "diff_total", "diff_total_all"]
            df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

            # print(f"columns {df.columns=}")

            load_data_to_database2(df, "all_rtt", db.get_connection())
            # df.to_sql(
            #     name="all_rtt",
            #     con=conn,
            #     if_exists="replace",
            #     index=False
            # )
        if not is_looping:
            break  # break out of outer loop

bad_rows[:5]

file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug25-ZIP-4M-71939.zip
Loaded 18531 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug25-ZIP-4M-71939.zip
Loaded 18531 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jul25-ZIP-4M-92707.zip
Loaded 18603 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jun25-ZIP-4M-94367.zip
Loaded 18542 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-May25-ZIP-4M-32711.zip
Loaded 18460 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Apr25-ZIP-4M-77252.zip
Loaded 18531 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Mar17-revised-ZIP-2872K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Feb17-revised-ZIP-2815K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jan17-revised-ZIP-2839K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Dec16-revised-ZIP-2753K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Nov16-revised-ZIP-2856K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Oct16-revised-ZIP-2826K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Sep16-revised-ZIP-3036K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug16-revised-ZIP-3009K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jul16-revised-ZIP-2977K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jun16-revised-ZIP-2995K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-May16-revised-ZIP-2989K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Apr16-revised-ZIP-2964K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Mar18-revised-ZIP-3051K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Feb18-revised-ZIP-3032K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jan18-revised-v2-ZIP-3086K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Dec17-revised-v2-ZIP-3135K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Nov17-revised-v2-ZIP-3058K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Oct17-revised-v2-ZIP-3084K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Sep17-ZIP-3092K-98673.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug17-revised-ZIP-3103K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jul17-revised-ZIP-3083K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jun17-revised-ZIP-3092K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-May17-revised-ZIP-3077K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Apr17-revised-ZIP-2963K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Mar19-revised-ZIP-3506K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Feb19-revised-ZIP-3485K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jan19-revised-ZIP-3634K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Dec18-ZIP-3427K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Nov18-revised-ZIP-3544K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Oct18-revised-ZIP-3574K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Sep18-revised-ZIP-K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug18-revised-ZIP-3464K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jul18-revised-ZIP-3450K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jun18-revised-ZIP-3426K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-May18-revised-ZIP-3424K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Apr18-revised-ZIP-3380K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Mar20-ZIP-2995K-73640.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Feb20-revised-ZIP-3171K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jan20-revised-ZIP-3227K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Dec19-revised-ZIP-3109K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Nov19-revised-ZIP-3528K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Oct19-revised-ZIP-3580K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Sep19-ZIP-3532K-62303.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug19-ZIP-3493K-revised.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jul19-ZIP-3550K-revised.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jun19-ZIP-3502K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-May19-ZIP-3497K-revised.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Apr19-ZIP-3436K-revised.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Mar21-ZIP-2888K-76325.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Feb21-ZIP-2739K-25692.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jan21-ZIP-2714K-24158.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Dec20-revised-ZIP-2860K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Nov20-ZIP-2758K-26885.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Oct20-revised-ZIP-2772K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Sep20-ZIP-2738K-20720.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug20-ZIP-2594K-09869.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jul20-ZIP-2546K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jun20-revised-ZIP-2649K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-May20-revised-ZIP-2216K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Apr20-revised-ZIP-2295K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Mar22-revised-ZIP-111805K.zip
Loaded 18925 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Feb22-revised-ZIP-109268K.zip
Loaded 18952 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jan22-revised-ZIP-4266K.zip
Loaded 18973 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Dec21-revised-ZIP-3744K.zip
Loaded 19065 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Nov21-revised-ZIP-3826K.zip
Loaded 18959 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Oct21-revised-ZIP-3787K.zip
Loaded 18903 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Sep21-revised-ZIP-3768K.zip
Loaded 18921 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug21-revised-ZIP-3682K.zip
Loaded 18891 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jul21-revised-ZIP-3710K.zip
Loaded 19015 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jun21-revised-ZIP-3739K.zip
Loaded 19098 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-May21-revised-ZIP-3656K.zip
Loaded 18986 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Apr21-revised-ZIP-3587K.zip
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Mar23-revised-ZIP-3589K.zip
Loaded 18796 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Feb23-revised-ZIP-3784K.zip
Loaded 18773 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jan23-revised-ZIP-3609K.zip
Loaded 18770 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Dec22-revised-ZIP-3631K.zip
Loaded 18580 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Nov22-revised-ZIP-3508K.zip
Loaded 18612 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Oct22-revised-ZIP-3473K.zip
Loaded 18642 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Sep22-revised-ZIP-3542K.zip
Loaded 18690 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug22-revised-ZIP-3488K.zip
Loaded 18735 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jul22-revised-ZIP-3642K.zip
Loaded 18601 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jun22-revised-ZIP-4253.zip
Loaded 18694 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-May22-revised-ZIP-4392K.zip
Loaded 18740 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Apr22-revised-ZIP-4253.zip
Loaded 18623 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Mar24-ZIP-3832K-revised.zip
Loaded 18391 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Feb24-ZIP-3881K-revised.zip
Loaded 18440 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jan24-ZIP-3943K-revised.zip
Loaded 18561 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Dec23-ZIP-3800K-revised.zip
Loaded 18440 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Nov23-ZIP-3952K-revised.zip
Loaded 18584 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Oct23-ZIP-3928K-revised.zip
Loaded 18597 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Sep23-ZIP-3654K-revised.zip
Loaded 18571 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug23-ZIP-3646K-revised.zip
Loaded 18505 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jul23-ZIP-3623K-revised.zip
Loaded 18569 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jun23-ZIP-3659K-64970.zip
Loaded 18676 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-May23-ZIP-3627K-revised.zip
Loaded 18614 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Apr23-ZIP-3528K-36960.zip
Loaded 18601 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Mar25-ZIP-4M-revised.zip
Loaded 18507 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Feb25-ZIP-4M-revised.zip
Loaded 18483 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jan25-ZIP-4M-revised.zip
Loaded 18467 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Dec24-ZIP-4M-revised.zip
Loaded 18430 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Nov24-ZIP-4M-revised.zip
Loaded 18610 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Oct24-ZIP-4M-revised.zip
Loaded 18598 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Sep24-ZIP-4M-revised.zip
Loaded 18546 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Aug24-ZIP-4M-revised.zip
Loaded 18426 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jul24-ZIP-4M-revised.zip
Loaded 18460 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Jun24-ZIP-4M-revised.zip
Loaded 18390 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-May24-ZIP-4M-revised.zip
Loaded 18375 rows into all_rtt
file is /home/tomhodder/.local/state/nhs_waiting_lists/files/rtt-waiting-times/Full-CSV-data-file-Apr24-ZIP-4M-revised.zip
Loaded 18354 rows into all_rtt

Empty DataFrame
Columns: [period, provider_org_code, rtt_part_type, treatment_function_code, gt_00_to_01_weeks, gt_01_to_02_weeks, gt_02_to_03_weeks, gt_03_to_04_weeks, gt_04_to_05_weeks, gt_05_to_06_weeks, gt_06_to_07_weeks, gt_07_to_08_weeks, gt_08_to_09_weeks, gt_09_to_10_weeks, gt_10_to_11_weeks, gt_11_to_12_weeks, gt_12_to_13_weeks, gt_13_to_14_weeks, gt_14_to_15_weeks, gt_15_to_16_weeks, gt_16_to_17_weeks, gt_17_to_18_weeks, gt_18_to_19_weeks, gt_19_to_20_weeks, gt_20_to_21_weeks, gt_21_to_22_weeks, gt_22_to_23_weeks, gt_23_to_24_weeks, gt_24_to_25_weeks, gt_25_to_26_weeks, gt_26_to_27_weeks, gt_27_to_28_weeks, gt_28_to_29_weeks, gt_29_to_30_weeks, gt_30_to_31_weeks, gt_31_to_32_weeks, gt_32_to_33_weeks, gt_33_to_34_weeks, gt_34_to_35_weeks, gt_35_to_36_weeks, gt_36_to_37_weeks, gt_37_to_38_weeks, gt_38_to_39_weeks, gt_39_to_40_weeks, gt_40_to_41_weeks, gt_41_to_42_weeks, gt_42_to_43_weeks, gt_43_to_44_weeks, gt_44_to_45_weeks, gt_45_to_46_weeks, gt_46_to_47_weeks, gt_47_to_48_weeks, gt_48_to_49_weeks, gt_49_to_50_weeks, gt_50_to_51_weeks, gt_51_to_52_weeks, gt_52_to_53_weeks, gt_53_to_54_weeks, gt_54_to_55_weeks, gt_55_to_56_weeks, gt_56_to_57_weeks, gt_57_to_58_weeks, gt_58_to_59_weeks, gt_59_to_60_weeks, gt_60_to_61_weeks, gt_61_to_62_weeks, gt_62_to_63_weeks, gt_63_to_64_weeks, gt_64_to_65_weeks, gt_65_to_66_weeks, gt_66_to_67_weeks, gt_67_to_68_weeks, gt_68_to_69_weeks, gt_69_to_70_weeks, gt_70_to_71_weeks, gt_71_to_72_weeks, gt_72_to_73_weeks, gt_73_to_74_weeks, gt_74_to_75_weeks, gt_75_to_76_weeks, gt_76_to_77_weeks, gt_77_to_78_weeks, gt_78_to_79_weeks, gt_79_to_80_weeks, gt_80_to_81_weeks, gt_81_to_82_weeks, gt_82_to_83_weeks, gt_83_to_84_weeks, gt_84_to_85_weeks, gt_85_to_86_weeks, gt_86_to_87_weeks, gt_87_to_88_weeks, gt_88_to_89_weeks, gt_89_to_90_weeks, gt_90_to_91_weeks, gt_91_to_92_weeks, gt_92_to_93_weeks, gt_93_to_94_weeks, gt_94_to_95_weeks, gt_95_to_96_weeks, ...]
Index: []

[0 rows x 115 columns]

In [20]:

df.query("provider_org_code == 'A4M8P' and rtt_part_type == 'Part_2'")

,period,provider_org_code,rtt_part_type,treatment_function_code,gt_00_to_01_weeks,gt_01_to_02_weeks,gt_02_to_03_weeks,gt_03_to_04_weeks,gt_04_to_05_weeks,gt_05_to_06_weeks,...,gt_98_to_99_weeks,gt_99_to_100_weeks,gt_100_to_101_weeks,gt_101_to_102_weeks,gt_102_to_103_weeks,gt_103_to_104_weeks,gt_104_weeks,patients_with_unknown_clock_start_date,total,total_all
24,2024-04,A4M8P,Part_2,C_100,46.0,106.0,62.0,69.0,47.0,83.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1349
25,2024-04,A4M8P,Part_2,C_101,13.0,35.0,25.0,16.0,14.0,22.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,799
26,2024-04,A4M8P,Part_2,C_110,13.0,13.0,16.0,13.0,7.0,22.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,452
27,2024-04,A4M8P,Part_2,C_120,30.0,23.0,45.0,25.0,12.0,25.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,589
28,2024-04,A4M8P,Part_2,C_160,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
29,2024-04,A4M8P,Part_2,C_170,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
30,2024-04,A4M8P,Part_2,C_301,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12
31,2024-04,A4M8P,Part_2,C_502,3.0,21.0,28.0,16.0,11.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,522
32,2024-04,A4M8P,Part_2,C_999,108.0,201.0,178.0,142.0,91.0,171.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3830
33,2024-04,A4M8P,Part_2,X02,3.0,2.0,2.0,2.0,0.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,92
34,2024-04,A4M8P,Part_2,X03,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
35,2024-04,A4M8P,Part_2,X06,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10